### ISSUE TITLE
Volunteer Page Hiccups

### ISSUE THREAD

**Issue by Gamer0278** [jhobz/rpglb#130]
A few blocks of text are misplaced from some shuffling, also some minor capitalization and spacing fixes that got lost in the shuffle between Bob and I's two versions.
[RPGLB2023 Volunteer Page.md](https://github.com/jhobz/rpglb/files/11474155/RPGLB2023.Volunteer.Page.md)

**Comment by jhobz** [comment]
For future reference, when it's more minor changes to an existing page instead of a major overhaul, you can also feel free to just enumerate the changes. The full markdown treatment is fine as well though!
